name: final_guitalele_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/iconImages/
   
flutter_launcher_icons:
  android: true
  ios: true
  # ios
  image_path: "final_guitalele_project/assets/images/logo.png"
  remove_alpha_ios: true
  # android
  adaptive_icon_foreground: "final_guitalele_project/assets/images/logo.png"
 

flutter_native_splash:
  

  image: "final_guitalele_project/assets/images/logo.png"
  android: true
  ios: true
  
    
